# fly.toml app configuration file generated for comp7940-lab-leiwuw2 on 2025-04-10T14:05:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "comp7940-lab-leiwuw2"
primary_region = "hkg"

[build]
dockerfile = "Dockerfile"  # 修正拼写

[env]
PORT = "8888"  # 确保应用监听此端口

[http_service]
internal_port = 8080       # 去掉下划线，与 PORT 环境变量一致
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1   # 保持至少 1 个实例运行
processes = ["app"]

[[services]]
internal_port = 8080       # 与 http_service 一致
protocol = "tcp"

[[services.ports]]
handlers = ["http"]        # 外部 80 端口转发到 8888
port = 80

[[services.ports]]
handlers = ["tls"]         # 外部 443 端口转发到 8888
port = 443

[[vm]]
size = "shared-cpu-1x"