# fly.toml app configuration file generated for comp7940-lab-leiwuw2 on 2025-04-10T14:05:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comp7940-lab-leiwuw2'
primary_region = 'hkg'

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  PORT = "8080"  # 告诉应用使用 8080 端口

[[services]]
  internal_port = 8080  # 容器内端口
  protocol = "tcp"